### ISSUE TITLE
Add initial tables

### ISSUE THREAD

**Issue by karanpopat** [turbot/steampipe-plugin-databricks#1]
Add initial tables:

- [x] databricks_account_budget
- [x] databricks_account_credential
- [x] databricks_account_custom_app_integration
- [x] databricks_account_user
- [x] databricks_account_encryption_keys
- [x] databricks_account_group
- [ ] databricks_account_ip_access_lists
- [ ] databricks_account_log_delivery
- [ ] databricks_account_metastore_assignments
- [ ] databricks_account_metastore
- [ ] databricks_account_network
- [ ] databricks_account_published_app_integration
- [ ] databricks_account_storage
- [ ] databricks_account_vpc_endpoint
- [ ] databricks_account_workspace
- [x] databricks_workspace_alert
- [x] databricks_workspace_catalog
- [x] databricks_workspace_cluster
- [x] databricks_workspace_cluster_policy
- [x] databricks_workspace_connection
- [x] databricks_workspace_current_user
- [x] databricks_workspace_dashboard
- [x] databricks_workspace_data_source
- [x] databricks_workspace_dbfs
- [x] databricks_workspace_experiment
- [x] databricks_workspace_external_location
- [x] databricks_workspace_function
- [x] databricks_workspace_git_credential
- [x] databricks_workspace_global_init_script
- [x] databricks_workspace_group
- [x] databricks_workspace_instance_pool
- [x] databricks_workspace_instance_profile
- [x] databricks_workspace_ip_access_list
- [x] databricks_workspace_job
- [x] databricks_workspace_job_run
- [x] databricks_workspace_metastore
- [x] databricks_workspace_model
- [x] databricks_workspace_pipeline
- [x] databricks_workspace_pipeline_event
- [x] databricks_workspace_pipeline_update
- [x] databricks_workspace_user
- [x] databricks_workspace_webhook

**Comment by karanpopat** [comment]
Getting error `Your token is missing the required scopes for this endpoint` in SDK. The same API passes with Databricks CLI using the same token.
Raised an issue in SDK for the same
https://github.com/databricks/databricks-sdk-go/issues/546

**Comment by karanpopat** [comment]
Thanks for the heads up @nfx on the AccountClient. I am proceeding with the other APIs from the WorkspaceClient for now.
Is there any other auth method recommendation you have that could be supported by the AccountClient as of now?

**Comment by nfx** [comment]
@karanpopat For account client we support azure cli, azure spn, Databricks CLI, Databricks account-level spn, and basic

**Comment by nfx** [comment]
@karanpopat Add initial tables - I'll see if it's possible to generate them

**Comment by karanpopat** [comment]
Error in get config for table `databricks_sql_dashboard`
https://github.com/databricks/databricks-sdk-go/issues/565
