### ISSUE TITLE
databricks_iam_account_user & databricks_iam_account_group Errors

### ISSUE THREAD

**Issue by oaulicino** [turbot/steampipe-plugin-databricks#5]
**Describe the bug**
Databricks tables databricks_iam_account_user & databricks_iam_account_group generate errors as below:
![image](https://github.com/turbot/steampipe-plugin-databricks/assets/31516700/2b7e8502-428b-4501-8e58-ebe7ca3c4b6e)

**Steampipe version (`steampipe -v`)**
v0.20.10

**Plugin version (`steampipe plugin list`)**
 hub.steampipe.io/plugins/turbot/databricks@latest    | 0.0.1   

**To reproduce**
I did not do anything out of ordinary, I simply ran
`select * from databricks_all.databricks_iam_account_user`
and
`select * from databricks_all.databricks_iam_account_group`
**Expected behavior**
I would expect it to work the same way all other tables work. I do have Account Admin Privileges so I would expect privileges not to be the issue here.

**Additional context**

**Comment by misraved** [comment]
Thank you @oaulicino for reporting the issue. We have fixed it in https://github.com/turbot/steampipe-plugin-databricks/pull/4

The latest plugin version `v0.1.0` includes the fix. Please give it a try and feel free to reopen this issue if you have more questions or feedback 👍.

**Comment by oaulicino** [comment]
Apologies, looks like what was working before with config_profile is no longer applicable, so I updated it to profile only in the spc file.
